// Graph module public exports

export { createGraphService } from './service'
export type { GraphService } from './service'
export { GraphClient } from './client'
export { initializeGraphDatabase, closeGraphDatabase, ensureGraphDirectory } from './database'
export { RpcClient, RpcServer } from './rpc'
export { GRAPH_IPC_VERSION, WorkerTransport, SocketTransport } from './ipc-transport'
export type { RpcTransport, IpcMessage } from './ipc-transport'
export { startIpcServer } from './ipc-server'
export type { IpcServer, IpcServerOptions } from './ipc-server'
export { encodeFrame, FrameDecoder, MAX_FRAME_BYTES } from './ipc-framing'
export { acquireLeader, readLeaderInfo, LEADER_LOCK_VERSION, LEADER_LOCK_FILENAME } from './leader-lock'
export type { LeaderInfo, LeaderHandle, AcquireOptions, AcquireResult, FollowerObservation } from './leader-lock'
export { LeaderLostError, isTransportFailure } from './errors'
export { READ_ONLY_METHODS, isReadOnlyMethod } from './read-only-methods'
export { RepoMap } from './repo-map'
export { TreeSitterBackend } from './tree-sitter'
export { FileCache } from './cache'
export { tokenize, computeMinHash, computeFragmentHashes, jaccardSimilarity } from './clone-detection'
export type { FragmentHash } from './clone-detection'
export * from './types'
export * from './constants'
export * from './utils'
